import { Stack_Sans_Notch } from "next/font/google";
import "./globals.css";

const SSN = Stack_Sans_Notch({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "R Bharathi Kumar | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={SSN.className}>
      <body className="">{children}</body>
    </html>
  );
}
